[package]
name = "battle_ship_game"
version = "0.1.0"
authors = ["xXGalacticWaferXx <mxgainzflex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
randomize = "3.0.1"
rand = "0.7.3"